name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: install cairo
        run: sudo apt-get install libcairo2-dev -y
      - name: setup linter
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.45.2
      - name: checkout code
        uses: actions/checkout@v2
      - name: test
        run: make test
      - name: lint
        run: make lint
      - name: integration test
        run: tests/system_test.sh
  # golangci:
  #   name: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
  #         version: v1.45.2
